backend:
  name: git-gateway
  branch: main # Or the branch your site builds from (e.g., master)
  auth_providers:
    - github
publish_mode: editorial_workflow # Optional: Enables draft/review/publish workflow
media_folder: "public/uploads" # Where media files will be stored in your repo
public_folder: "/uploads" # Path to access media files on your site

collections:
  - name: "pages" # A friendly name for your content type
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md" # This is where Netlify CMS will save your "Home" page content.
        # === ADDED THIS FIELDS SECTION ===
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
        # =================================

